### ISSUE TITLE
Parameter template

### ISSUE THREAD

**Issue by pedrevans** [dbdahl/rscala#17]
This is not so much an issue, rather my inability to understand how to use the package properly.

I thought I could do something like the following:
```
    val rStringLength = "function(s) return(nchar(s))"
    val rStrLenFun = R.evalObject(rStringLength)
    val helloLen = R.evalI0("%-", rStrLenFun, "hello")
    println("Length of hello is "+helloLen)
```
but that doesn't work.

If I replace the "helloLen" line above with the following:

```
    val helloLen = R.evalI0("%-(\"hello\")", rStrLenFun)
```
then I get the desired effect. But that doesn't seem to be how it should work.

Am I doing something stupid?

**Comment by dbdahl** [comment]
Another variant (which might help in understanding the proper usage) is this:

`val helloLen = R.evalI0("%-(%-)", rStrLenFun, "hello")`

The first argument is a template string and you should think about "%-" as being a placeholder for an R object (like rStrLenFun) or literal (like "hello").

In your first attempt, the result is invalid R code (because you are missing parentheses):

`foo"hello"`

where "foo" is an internal variable equal to "rStrLenFun".

**Comment by pedrevans** [comment]
Brilliant. Ok, it's clicked now. Thanks a lot for the explanation.

Is that R bytecode that ends up in the object "rStrLenFun"?

**Comment by dbdahl** [comment]
In Scala, the object "rStrLenFun" contains an Array[Byte] resulting from the "serialize" function in R.  Passing it back to R involves a call to R's "unserialize" function.  This serialization is somewhat costly for large R objects.  To avoid this, you might consider something like the following.  (Note the use of Scala string interpolation.)

```
val R = org.ddahl.rscala.RClient()
val functionName = "foo"
val rStringLength = s"$functionName <- function(s) return(nchar(s))"
R.eval(rStringLength)
val helloLen = R.evalI0(s"$functionName(%-)", "hello")
println("Length of hello is "+helloLen)
```
