### ISSUE TITLE
Question on the ping and exit methods of RClient

### ISSUE THREAD

**Issue by bithw1** [dbdahl/rscala#3]
Hi, @dbdahl ,
I am reading the code of RClient at https://github.com/dbdahl/rscala/blob/master/src/main/scala/org/ddahl/rscala/RClient.scala,

There is an instance of Process, rProcessInstance , I would ask what this process stands for?

It looks to me that the `ping `and `exit `methods should be reconsidered,
I think a common pattern to use ping and exit may be:

```
if (!R.ping()) {
  R.exit()
}

```
If ping returns false, and the process has been destroyed, then calling on exit would do nothing but throw error.
I think the code for ping and exit can be improves as following, that is ,check whether rProcessInstance  has been destroyed? 

```
  def ping(): Boolean = synchronized {
      try {
        if (rProcessInstance != null) {
          out.writeInt(PING)
          out.flush()
          val status = in.readInt()
          status == OK
        } else {
          false
        }

      } catch {
        case _ : Throwable =>
          if ( rProcessInstance != null ) {
            rProcessInstance.destroy()
            rProcessInstance = null
          }
          false
      }
    }



    def exit() = synchronized {
      try {
        if (rProcessInstance != null) {
          check4GC()
          out.writeInt(SHUTDOWN)
          out.flush()
        }
      } catch {
        case _ : Throwable => {
          rProcessInstance.destroy()
          rProcessInstance = null
        }
      }


    }
```

**Comment by dbdahl** [comment]
I'm not sure a change is warranted.  Please read below and let me know if you disagree.

Regarding rProcessInstance and the meaning of it being null, the rscala package allows: 1. R to be embedded in a Scala application (that's your application) and 2. allows Scala to be embedded in an R application.  **The RClient class is used in both directions.**

In the first case, the rProcessInstance represents the R process started by one of the "apply" methods of the RClient companion object, e.g., "val R = org.ddahl.rscala.RClient()".  In this case, rProcessInstance will never be null, even after the "destroy" method is called.

In the second case, the RClient does not own the R process (that is, JVM itself is started by R) and, in that case, rProcessInstance is null.  Hence, before calling the "destroy" method of rProcessInstance, there is a check to see if it is null.

The "exit" method has two functions, depending on the case.  In the first case, it asks R to gracefully exit. 
 In the second case, it asks the embedded R server to exit (but R continues to run).  Calling "exit", "set", "get", "eval", and any of their related functions (e.g., "evalD0", "getS0") on an invalid RClient will throw an exception.  An RClient can become invalid (in the first case) because the "exit" method has already been called or somehow the underlying R process has been killed the user or operating system.  The user can check that the RClient is still valid by calling the "ping" method.  If the ping fails, there is no point in calling the "exit" method because the connection is broken and there is no way to ask R to gracefully exit.

**Comment by bithw1** [comment]
Thanks @dbdahl for the detailed explanation, I agree with you, I got a question, you mentioned two  modes,
1. R to be embedded in a Scala application
2. allows Scala to be embedded in an R application

In the 1st option, there is no RServe involved and in the 2nd option,there is an RServ Process involved?

**Comment by dbdahl** [comment]
In both modes, an custom-written, embedded R server is involved.  In the first case (R in an Scala application), the R server receives commands from Scala.  In the second case (Scala embedded in an R application), the embedded R server receives any callbacks from the running Scala snippet.  Note that this R server is not related to [Rserve](https://www.rforge.net/Rserve/).

**Comment by bithw1** [comment]
@dbdahl 
After further thinking, In my opinion, `ping` is a method that should not have side effect, it simply answer the question whether the RClient is usable or not any more. It is the user's responsibility to release the resource by calling `exit`, and  user expects that `exit`  will have side effect since resource is released.

So, I think the following code in 'ping' should move into `exit`
```
      if ( rProcessInstance != null ) {
            rProcessInstance.destroy()
            rProcessInstance = null
          }
```

I am using Apache Object Pool framework(http://commons.apache.org/proper/commons-pool/) to pool the RClient object. The pool framework has two methods: 
(1)validateObject: to check whether the object is valid
(2)destroyObject:If the object is invalid,then destroy the object

These two methods can be easily implemented with `ping `and `exit` if `ping' and 'exit' works in the way that I said above

**Comment by dbdahl** [comment]
@bithw1 I have no objections and it is implemented here:

https://github.com/dbdahl/rscala/commit/2e76f1ae9fd5c604671ba183afd31e9c4249cce2

Unless the next release, you can access the updated JAR files here:

https://dahl.byu.edu/public/rscalaJars_LATEST.tar.gz

and the R package is here:

https://dahl.byu.edu/public/rscala_LATEST.tar.gz

**Comment by bithw1** [comment]
Thanks @dbdahl  for the update.
